# Generated by Django 2.2 on 2021-02-18 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='from_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='history',
            name='to_year',
            field=models.IntegerField(default=0),
        ),
    ]
